services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "5000:5000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - ./app/data:/app/data

  ollama:
    build:
      context: .
      dockerfile: dockerfile-ollama
    container_name: ollama
    ports:
      - "11434:11434"

